cluster:
  name: lab1
hubble:
  relay:
    enabled: true
  ui:
    enabled: true
    ingress:
      enabled: true
      hosts:
        - hubble.lab.hvlck.xyz
ipam:
  mode: cluster-pool
  operator:
    clusterPoolIPv4MaskSize: 24
    clusterPoolIPv4PodCIDRList: 10.244.0.0/16
k8sServiceHost: lab1-control-plane
k8sServicePort: 6443
kubeProxyReplacement: true
operator:
  replicas: 1
localRedirectPolicy: true
envoy:
  enabled: false
