kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: lab1
nodes:
- role: control-plane
  image: kindest/node:v1.30.6@sha256:b6d08db72079ba5ae1f4a88a09025c0a904af3b52387643c285442afb05ab994
  kubeadmConfigPatches:
  - |
    kind: ClusterConfiguration
    apiServer:
        extraArgs:
          admission-control-config-file: /etc/kubernetes/admissionconfiguration.yaml
          enable-admission-plugins: ExtendedResourceToleration,NodeRestriction
        extraVolumes:
        - name: etc-kubernetes-admissionconfiguration
          hostPath: /etc/kubernetes/admissionconfiguration.yaml
          mountPath: /etc/kubernetes/admissionconfiguration.yaml
          pathType: File
          readOnly: true
  extraMounts:
  - hostPath: admissionconfiguration.yaml
    containerPath: /etc/kubernetes/admissionconfiguration.yaml
    readOnly: true
- role: worker
  image: kindest/node:v1.30.6@sha256:b6d08db72079ba5ae1f4a88a09025c0a904af3b52387643c285442afb05ab994
  extraPortMappings:
  - containerPort: 80
    hostPort: 80
  - containerPort: 443
    hostPort: 443
- role: worker
  image: kindest/node:v1.30.6@sha256:b6d08db72079ba5ae1f4a88a09025c0a904af3b52387643c285442afb05ab994
networking:
  disableDefaultCNI: true
  podSubnet: "10.244.0.0/16"
  serviceSubnet: "10.96.0.0/16"
