kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: lab1
nodes:
- role: control-plane
  image: kindest/node:v1.31.2@sha256:18fbefc20a7113353c7b75b5c869d7145a6abd6269154825872dc59c1329912e
  kubeadmConfigPatches:
  - |
    kind: ClusterConfiguration
    apiServer:
        extraArgs:
          admission-control-config-file: /etc/kubernetes/admissionconfiguration.yaml
          enable-admission-plugins: ExtendedResourceToleration,NodeRestriction
        extraVolumes:
        - name: etc-kubernetes-admissionconfiguration
          hostPath: /etc/kubernetes/admissionconfiguration.yaml
          mountPath: /etc/kubernetes/admissionconfiguration.yaml
          pathType: File
          readOnly: true
  extraMounts:
  - hostPath: admissionconfiguration.yaml
    containerPath: /etc/kubernetes/admissionconfiguration.yaml
    readOnly: true
- role: worker
  image: kindest/node:v1.31.2@sha256:18fbefc20a7113353c7b75b5c869d7145a6abd6269154825872dc59c1329912e
  extraPortMappings:
  - containerPort: 80
    hostPort: 80
  - containerPort: 443
    hostPort: 443
- role: worker
  image: kindest/node:v1.31.2@sha256:18fbefc20a7113353c7b75b5c869d7145a6abd6269154825872dc59c1329912e
networking:
  disableDefaultCNI: true
  podSubnet: "10.244.0.0/16"
  serviceSubnet: "10.96.0.0/16"
