kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: lab1
nodes:
- role: control-plane
  image: kindest/node:v1.31.0@sha256:53df588e04085fd41ae12de0c3fe4c72f7013bba32a20e7325357a1ac94ba865
  kubeadmConfigPatches:
  - |
    kind: ClusterConfiguration
    apiServer:
        extraArgs:
          admission-control-config-file: /etc/kubernetes/admissionconfiguration.yaml
          enable-admission-plugins: ExtendedResourceToleration,NodeRestriction
        extraVolumes:
        - name: etc-kubernetes-admissionconfiguration
          hostPath: /etc/kubernetes/admissionconfiguration.yaml
          mountPath: /etc/kubernetes/admissionconfiguration.yaml
          pathType: File
          readOnly: true
  extraMounts:
  - hostPath: admissionconfiguration.yaml
    containerPath: /etc/kubernetes/admissionconfiguration.yaml
    readOnly: true
- role: worker
  image: kindest/node:v1.31.0@sha256:53df588e04085fd41ae12de0c3fe4c72f7013bba32a20e7325357a1ac94ba865
  extraPortMappings:
  - containerPort: 80
    hostPort: 80
  - containerPort: 443
    hostPort: 443
- role: worker
  image: kindest/node:v1.31.0@sha256:53df588e04085fd41ae12de0c3fe4c72f7013bba32a20e7325357a1ac94ba865
networking:
  disableDefaultCNI: true
  podSubnet: "10.244.0.0/16"
  serviceSubnet: "10.96.0.0/16"
