controller:
  enableAnnotationValidations: true
  config:
    use-proxy-protocol: "true"
  dnsPolicy: ClusterFirstWithHostNet
  reportNodeInternalIp: true
  watchIngressWithoutClass: true
  allowSnippetAnnotations: true
  hostNetwork: true
  hostPort:
    enabled: true
    ports:
      http: 80
      https: 443
  ingressClassResource:
    default: true
  kind: DaemonSet
  publishService:
    enabled: false
  service:
    enabled: false
